name: Auto Commit (10x Daily)

permissions:
  contents: write

on:
  schedule:
    - cron: "0 1,3,5,7,9,11,13,15,17,19 * * *"
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --local user.email "rezawalker02@gmail.com"
          git config --local user.name "walkerreza"

      - name: Update file
        run: |
          echo "Update at $(date -u)" > LAST_UPDATED

      - name: Commit
        run: |
          git add LAST_UPDATED
          git commit -m "Penghijauan" || echo "No changes"

      - name: Push
        run: git push
